version: 2
updates:

# Maintain dependencies for GitHub Actions 
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
    labels:
      - dependencies
    commit-message:
      prefix: "⬆️ Actions"
    rebase-strategy: auto

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - dependencies
    commit-message:
      prefix: "⬆️ NPM"
    rebase-strategy: auto