query getExpandedPostDocument($relativePath: String!) {
  post(relativePath: $relativePath) {
    _sys {
      filename
      basename
      breadcrumbs
      path
      relativePath
      extension
    }
    id
    title
    date
    last_edited
    author
    prev {
      ... on Post {
        id
        title
      }
    }
    next {
      ... on Post {
        id
        title
      }
    }
    body
  }
}

query pageWithRecentPosts($relativePath: String!) {
  page(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PageParts
  }
  recentPosts: postConnection(sort: "date", last: 2) {
    edges {
      node {
        _sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
        }
        ...PostParts
      }
    }
  }
}