fragment PageParts on Page {
  seo {
    __typename
    title
    description
  }
  blocks {
    __typename
    ... on PageBlocksHero {
      headline
      text
      actions {
        __typename
        label
        icon
        variant
        size
        url
      }
      videoSrc
    }
    ... on PageBlocksFeatures {
      items {
        __typename
        ... on PageBlocksFeaturesItemsFeature {
          headline
          text
          media {
            __typename
            src
            videoSrc
            cli
          }
          actions {
            __typename
            label
            icon
            variant
            size
            url
          }
        }
      }
    }
    ... on PageBlocksFlying {
      headline
      text
      actions {
        __typename
        label
        icon
        variant
        size
        url
      }
    }
    ... on PageBlocksPricing {
      intro
      base {
        __typename
        name
        price
        interval
        body
        actions {
          __typename
          label
          icon
          variant
          size
          url
        }
      }
      plans {
        __typename
        name
        price
        interval
        body
        actions {
          __typename
          label
          icon
          variant
          size
          url
        }
      }
    }
    ... on PageBlocksFaq {
      title
      intro
      questions {
        __typename
        question
        answer
      }
      color
    }
    ... on PageBlocksContent {
      options {
        __typename
        narrow
        color
        align
      }
      content
    }
    ... on PageBlocksShowcase {
      items {
        __typename
        headline
        text
        url
        media {
          __typename
          src
        }
      }
    }
    ... on PageBlocksColumns {
      options {
        __typename
        columns
        narrow
        color
        align
      }
      columnOne
      columnTwo
    }
    ... on PageBlocksStory {
      title
    }
    ... on PageBlocksFeatureGrid {
      items {
        __typename
        headline
        text
        actions {
          __typename
          label
          icon
          variant
          size
          url
        }
      }
    }
    ... on PageBlocksLogoGrid {
      title
      link
      items {
        __typename
        name
        logo
        size
      }
    }
    ... on PageBlocksRoadmapGrid {
      headline
      items {
        __typename
        headline
        status
        content
        actions {
          __typename
          label
          icon
          variant
          size
          url
        }
      }
      options {
        __typename
        paddingTop
        paddingBottom
      }
    }
    ... on PageBlocksRecentPosts {
      title
    }
  }
}

fragment DocParts on Doc {
  title
  last_edited
  prev
  next
  body
}

fragment PostParts on Post {
  title
  date
  last_edited
  author
  prev {
    ... on Post {
      title
      date
      last_edited
      author
      prev {
        ... on Post {
          title
          date
          last_edited
          author
          body
        }
        ... on Document {
          id
        }
      }
      next {
        ... on Post {
          title
          date
          last_edited
          author
          body
        }
        ... on Document {
          id
        }
      }
      body
    }
    ... on Document {
      id
    }
  }
  next {
    ... on Post {
      title
      date
      last_edited
      author
      prev {
        ... on Post {
          title
          date
          last_edited
          author
          body
        }
        ... on Document {
          id
        }
      }
      next {
        ... on Post {
          title
          date
          last_edited
          author
          body
        }
        ... on Document {
          id
        }
      }
      body
    }
    ... on Document {
      id
    }
  }
  body
}

fragment AbtestParts on Abtest {
  tests {
    __typename
    testId
    href
    variants {
      __typename
      testId
      href
    }
  }
}
