query getExpandedPostDocument($relativePath: String!) {
  post(relativePath: $relativePath) {
    _sys {
      filename
      basename
      breadcrumbs
      path
      relativePath
      extension
    }
    id
    title
    date
    last_edited
    author
    seo {
      title
      description
    }
    prev {
      ... on Post {
        id
        title
      }
    }
    next {
      ... on Post {
        id
        title
      }
    }
    body
  }
}

query getExpandedPostZhDocument($relativePath: String!) {
  postZh(relativePath: $relativePath) {
    _sys {
      filename
      basename
      breadcrumbs
      path
      relativePath
      extension
    }
    id
    title
    date
    last_edited
    author
    seo {
      title
      description
    }
    prev {
      ... on PostZh {
        id
        title
      }
      ... on Post {
        id
        title
      }
    }
    next {
      ... on PostZh {
        id
        title
      }
      ... on Post {
        id
        title
      }
    }
    body
  }
}

query pageWithRecentPosts($relativePath: String!) {
  page(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PageParts
  }
  recentPosts: postConnection(sort: "date", last: 3) {
    edges {
      node {
        _sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
        }
        ...PostParts
      }
    }
  }
}

query pageZhWithRecentPosts($relativePath: String!) {
  page(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PageParts
  }
  recentPosts: postZhConnection(sort: "date", last: 2) {
    edges {
      node {
        _sys {
          filename
          basename
          breadcrumbs
          path
          relativePath
          extension
        }
        ...PostZhParts
      }
    }
  }
}

query getAllDocs {
  docConnection(first: 1000) {
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
      }
    }
  }
}

query postSlugs($after: String) {
  postConnection(after: $after) {
    pageInfo {
      hasNextPage
      endCursor
    }
    edges {
      node {
        _sys {
          filename
        }
      }
    }
  }
}

query postZhSlugs($after: String) {
  postZhConnection(after: $after) {
    pageInfo {
      hasNextPage
      endCursor
    }
    edges {
      node {
        _sys {
          filename
        }
      }
    }
  }
}

query postCursors($first: Float, $sort: String) {
  postConnection(first: $first, sort: $sort) {
    edges {
      cursor
    }
  }
}

query postZhCursors($first: Float, $sort: String) {
  postZhConnection(first: $first, sort: $sort) {
    edges {
      cursor
    }
  }
}

query postPage($first: Float, $after: String, $sort: String) {
  postConnection(first: $first, after: $after, sort: $sort) {
    edges {
      node {
        id
        _sys {
          filename
        }
        title
        author
        date
        body
      }
    }
  }
}

query postZhPage($first: Float, $after: String, $sort: String) {
  postZhConnection(first: $first, after: $after, sort: $sort) {
    edges {
      node {
        id
        _sys {
          filename
        }
        title
        author
        date
        body
      }
    }
  }
}
